name: Build Image
inputs:
  directory:
    description: 'Directory where the image is located'
    required: true

runs:
  using: composite
  steps:
    - name: Prepare .env file
      run: |
        set -o pipefail -o errexit -o nounset
        cp .ci.env .env

    - name: Calculate Outputs
      id: calculation
      run: |
        set -o pipefail -o errexit -o nounset
        cd ${{ inputs.directory }}
        [ -f Dockerfile ] && IS_IMAGE="true" || IS_IMAGE="false"

        echo "is_image=$IS_IMAGE" | tee -a $GITHUB_OUTPUT
        echo "list=$(make list | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT
        echo "list_base=$(make list-base | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT
        echo "list_baseless=$(make list-baseless | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT
