IMAGE := base-alpine
VERSIONS := 3.21 edge

# The include should happen after all variables are defined because the
# included Makefile may rely on these variables.
include ../../.makefiles/docker.Makefile
