#!/bin/sh

create_dir() {
  for dir in "$@"; do
    # Create directory if it doesn't exist
    [ -d "$dir" ] || mkdir -p "$dir"
    # ensure correct ownership
    chown nicotine:nicotine "$dir"
  done
}

main() {
  create_dir \
    "/home/nicotine" \
    "/home/nicotine/.local" \
    "/home/nicotine/.local/share" \
    "/home/nicotine/.local/share/nicotine" \
    "/home/nicotine/.local/share/nicotine/downloads" \
    "/home/nicotine/.local/share/nicotine/incomplete" \
    "/home/nicotine/.config" \
    "/home/nicotine/.config/nicotine"

  su - nicotine -c 'env GDK_BACKEND=broadway GTK_OVERLAY_SCROLLING=0 BROADWAY_DISPLAY=:5 nicotine'
}

main >> /var/log/svc/nicotine-plus.log 2>&1
