IMAGE := ansible-target-fedora
VERSIONS := 43 44 rawhide
SHELL_CMD := bash

# The include should happen after all variables are defined because the
# included Makefile may rely on these variables.
include ../../.makefiles/docker.Makefile
