IMAGE := ansible-target-ubuntu
VERSIONS := 22.04 24.04

# The include should happen after all variables are defined because the
# included Makefile may rely on these variables.
include ../../.makefiles/docker.Makefile
