IMAGE := base-ubuntu
VERSIONS := 22.04 24.04
SHELL_CMD := bash

# The include should happen after all variables are defined because the
# included Makefile may rely on these variables.
include ../../.makefiles/docker.Makefile
