---
##
# This is a GitHub Actions workflow that builds Docker images
##

name: Build (Layer 2)

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  preflight:
    # checkout, determine whether this is an image or directory
    runs-on: ubuntu-24.04
    outputs:
      is_image: ${{ steps.calculation.outputs.is_image }}
      list: ${{ steps.calculation.outputs.list }}
      list_base: ${{ steps.calculation.outputs.list_base }}
      list_baseless: ${{ steps.calculation.outputs.list_baseless }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare .env file
        run: |
          set -o pipefail -o errexit -o nounset
          cp .ci.env .env

      - name: Calculate Outputs
        id: calculation
        run: |
          set -o pipefail -o errexit -o nounset
          cd ${{ inputs.directory }}
          [ -f Dockerfile ] && IS_IMAGE="true" || IS_IMAGE="false"

          echo "is_image=$IS_IMAGE" | tee -a $GITHUB_OUTPUT
          echo "list=$(make list | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT
          echo "list_base=$(make list-base | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT
          echo "list_baseless=$(make list-baseless | jq -R -c 'split(" ")')" | tee -a $GITHUB_OUTPUT

  # # If this directory represents an image that can be built, build it
  # build:

  # if this directory represents a folder with multiple images, build
  # the base images (if any)
  build-base:
    needs: preflight
    if: needs.preflight.outputs.is_image == 'false'
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.preflight.outputs.list_base) }}
    uses: ./.github/workflows/build-dir-3.yaml
    with:
      directory: ${{ matrix.directory }}


  # if this directory represents a folder with multiple images, build
  # the non-base images (if any)
  build-non-base:
    needs: [preflight, build-base]
    if: needs.preflight.outputs.is_image == 'false'
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.preflight.outputs.list_baseless) }}
    uses: ./.github/workflows/build-dir-3.yaml
    with:
      directory: ${{ matrix.directory }}


  # if this directory represents an image, build it
  build-image:
    needs: preflight
    if: needs.preflight.outputs.is_image == 'true'
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.preflight.outputs.list) }}
    runs-on: "${{ contains(matrix.variant, 'arm64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}"
    steps:
      - uses: ./.github/actions/build-image
        with:
          directory: ${{ inputs.directory }}
          variant: ${{ matrix.variant }}

