
on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
      variant:
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare .env file
        run: |
          echo "Hi!"
