---
##
# This is a GitHub Actions workflow that builds Docker images
##


name: Build Docker Images

env:
  NAMESPACE: adduc

on:
  push:

  # workflow_call:
  #   inputs:

# Ensure that there is only ever one build running at a time for a given
# branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  preflight:
    # checkout, determine whether this is an image or directory
    runs-on: ubuntu-24.04
    outputs:
      is_image: ${{ steps.is-image.outputs.is_image }}
      list: ${{ steps.list.outputs.list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine if this is an image or directory
        id: is-image
        run: |
          set -o pipefail -o errexit -o nounset
          [ -f Dockerfile ] && IS_IMAGE="true" || IS_IMAGE="false"
          echo "is_image=$IS_IMAGE" >> $GITHUB_OUTPUT

      - name: List variants/directories
        id: list
        run: |
          set -o pipefail -o errexit -o nounset
          echo "list=$(make list)" >> $GITHUB_OUTPUT

  # # If this directory represents an image that can be built, build it
  # build:


  # # if this directory represents a folder with multiple images, build
  # # the base images (if any)
  # build-base:

  # # if this directory represents a folder with multiple images, build
  # # the non-base images (if any)
  # build-non-base:


# workflowBuild (directory=.,variant=null):
#   list variants (if possible)
#     -> build each variant
#   find base* directories with Makefile
#     -> call workflowBuild with directory
#   find non-base directories with Makefile
#     -> call workflowBuild with directory


# With this approach:
# - we allow up to four layers of image dependencies in a single workflow
# - we allow every image (including variants) to be built in parallel
# - workflowBuild could be dispatched with a specific directory and variant to build a single image
# - workflowBuild could be scheduled to run periodically, e.g. every week
