---
##
# This is a GitHub Actions workflow that builds Docker images
##

name: Build (Layer 3)

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  gather-metadata:
    uses: ./.github/workflows/gather-metadata.yaml
    with:
      directory: ${{ inputs.directory }}

  # # If this directory represents an image that can be built, build it
  # build:

  # if this directory represents a folder with multiple images, build
  # the base images (if any)
  build-base:
    needs: gather-metadata
    if: needs.gather-metadata.outputs.is_image == 'false'
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.gather-metadata.outputs.list_base) }}
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "Due to workflow depth limitations, we cannot build this image."
          exit 1


  # if this directory represents a folder with multiple images, build
  # the non-base images (if any)
  build-non-base:
    needs: [gather-metadata, build-base]
    if: needs.gather-metadata.outputs.is_image == 'false'
    strategy:
      fail-fast: false
      matrix:
        directory: ${{ fromJson(needs.gather-metadata.outputs.list_baseless) }}
    runs-on: ubuntu-24.04
    steps:
      - run: |
          echo "Due to workflow depth limitations, we cannot build this image."
          exit 1

  # if this directory represents an image, build it
  build-image:
    needs: gather-metadata
    if: needs.gather-metadata.outputs.is_image == 'true'
    strategy:
      fail-fast: false
      matrix:
        variant: ${{ fromJson(needs.gather-metadata.outputs.list) }}
    runs-on: "${{ contains(matrix.variant, 'arm64') && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-image
        with:
          directory: ${{ inputs.directory }}
          variant: ${{ matrix.variant }}

